"""
    alignment.jl — Expose simulator timings as token–frame ranges.

The simulator already has full timings (TimedMorseEvent per element; transmission_ranges).
This module does not "align" or estimate; it reports which tokens (letters/specials)
belong to which time/frame ranges by converting the simulator's times to frame indices.
Downstream (e.g. MorseDecoder) uses TokenTiming to slice chunks so each chunk's
labels match the spectrogram. Token order matches decoder tokenization.
"""

"""
    AbstractTokenTiming

Supertype for token-to-frame alignment. Use `TokenTiming` when alignment is available,
`NoTiming` when it is not (e.g. alignment failed or not computed). Enables dispatch
without Union or conditionals.
"""
abstract type AbstractTokenTiming end

"""
    TokenTiming

Per-token frame ranges for the label. Same length as the token sequence
(label_to_token_ids(label) in decoder terms).

# Fields
- `token_start_frames::Vector{Int}` — 1-based start frame index per token
- `token_end_frames::Vector{Int}` — 1-based end frame index per token (inclusive)
"""
struct TokenTiming <: AbstractTokenTiming
    token_start_frames::Vector{Int}
    token_end_frames::Vector{Int}
end

"""No token timing available; use proportional mapping downstream."""
struct NoTiming <: AbstractTokenTiming end

# Match decoder special token strings so tokenization aligns (no leading _ per style)
const LABEL_SPECIAL_START = "<START>"
const LABEL_SPECIAL_END   = "<END>"
const LABEL_SPECIAL_TS    = "[TS]"
const LABEL_SPECIAL_TE    = "[TE]"
const LABEL_SPEAKER_TAGS  = ["[S1]", "[S2]", "[S3]", "[S4]", "[S5]", "[S6]"]
const LABEL_SPECIALS      = Set(String[LABEL_SPECIAL_START, LABEL_SPECIAL_END, LABEL_SPECIAL_TS, LABEL_SPECIAL_TE, LABEL_SPEAKER_TAGS...])

"""
    character_time_ranges(text, events) -> Vector{Tuple{Float64,Float64}}

Return (start_time, end_time) in seconds for each character (and space between words)
in `text`, using the timed events for that transmission. Events must be in the same
order as produced by text_to_timed_events for this text.

Produces exactly one range per character plus one range per inter-word space,
matching what label_to_token_ids produces token-wise. Prosigns are expanded to
per-character ranges (proportional split). Unknown characters get zero-width ranges.
"""
function character_time_ranges(text::AbstractString, events::Vector{TimedMorseEvent{Float64}})
    out = Tuple{Float64, Float64}[]
    isempty(events) && return out
    ev_idx = 1
    words = split(strip(text))
    for (wi, word) in enumerate(words)
        word_str = String(word)
        if is_prosign(word_str)
            # Prosign: sent as a single Morse unit (no char gaps), but the label
            # contains one token per character. Consume events for the whole prosign,
            # then split the time range proportionally across characters.
            symbols = prosign_to_morse(word_str)
            n_sym = length(symbols)
            if n_sym == 0
                # Degenerate prosign with no Morse — zero-width per char
                t = ev_idx <= length(events) ? events[ev_idx].start_time :
                    (events[end].start_time + events[end].duration)
                for _ in 1:length(word_str)
                    push!(out, (t, t))
                end
            else
                # Events: n_sym elements + (n_sym - 1) symbol gaps = 2*n_sym - 1
                n_ev = 2 * n_sym - 1
                ev_end = ev_idx + n_ev - 1
                if ev_end > length(events)
                    error("character_time_ranges: ran out of events for prosign \"$word_str\" " *
                          "(ev_idx=$ev_idx, need $n_ev events, have $(length(events)))")
                end
                t_start = events[ev_idx].start_time
                t_end = events[ev_end].start_time + events[ev_end].duration
                # Split proportionally across characters
                n_chars = length(word_str)
                dt = (t_end - t_start) / n_chars
                for ci in 1:n_chars
                    push!(out, (t_start + (ci - 1) * dt, t_start + ci * dt))
                end
                ev_idx = ev_end + 1
            end
        else
            # Regular word: one Morse unit per character
            symbols_list = [char_to_morse(c) for c in word_str]
            for (ci, symbols) in enumerate(symbols_list)
                if isempty(symbols)
                    # Unknown character — no events were generated by text_to_timed_events,
                    # so don't consume any. Emit a zero-width range at the current position.
                    t = ev_idx <= length(events) ? events[ev_idx].start_time :
                        (events[end].start_time + events[end].duration)
                    push!(out, (t, t))
                    continue
                end
                n_sym = length(symbols)
                # Events for this character: n_sym elements + (n_sym - 1) symbol gaps
                n_ev = 2 * n_sym - 1
                # Char gap after current char — must mirror text_to_timed_events logic:
                # it checks `ci < length(symbols_list)` regardless of whether the NEXT
                # char is empty. Since text_to_timed_events also `continue`s on empty,
                # we need to check if any SUBSEQUENT char actually has Morse content.
                has_char_gap = false
                if ci < length(symbols_list)
                    # text_to_timed_events adds char gap when ci < length(symbols_list),
                    # BUT it will have skipped empty entries before this one. The gap is
                    # only present if the CURRENT char is not the last non-empty char and
                    # text_to_timed_events's loop index < length(symbols_list).
                    # Since text_to_timed_events iterates `ci` over ALL entries (including
                    # empty ones that get skipped), the char gap is emitted whenever the
                    # loop index ci < length(symbols_list) for a NON-EMPTY entry.
                    has_char_gap = true
                    n_ev += 1
                end
                ev_end = ev_idx + n_ev - 1
                if ev_end > length(events)
                    error("character_time_ranges: ran out of events for char '$(word_str[ci])' " *
                          "in word \"$word_str\" (ev_idx=$ev_idx, need $n_ev, have $(length(events)))")
                end
                t_start = events[ev_idx].start_time
                t_end = events[ev_end].start_time + events[ev_end].duration
                push!(out, (t_start, t_end))
                ev_idx = ev_end + 1
            end
        end
        # Word gap (one event) between words → we emit a (start,end) for the space token
        if wi < length(words)
            if ev_idx > length(events)
                error("character_time_ranges: ran out of events for word gap after \"$word_str\" " *
                      "(ev_idx=$ev_idx, have $(length(events)))")
            end
            t_start = events[ev_idx].start_time
            t_end = t_start + events[ev_idx].duration
            push!(out, (t_start, t_end))
            ev_idx += 1
        end
    end
    return out
end

"""
    compute_token_timings(transcript, scene_events) -> Tuple{Vector{Float64}, Vector{Float64}}

Return (start_times, end_times) in seconds, one entry per token in label order.
Errors if alignment cannot be computed (indicates a simulator bug).
"""
function compute_token_timings(
    transcript::Transcript,
    scene_events::SceneMorseEvents{Float64},
)::Tuple{Vector{Float64}, Vector{Float64}}
    sorted_txs = sort(collect(transcript.transmissions), by = tx -> tx.time_offset)
    if length(scene_events.transmission_ranges) != length(sorted_txs)
        error("compute_token_timings: transmission_ranges count ($(length(scene_events.transmission_ranges))) " *
              "!= sorted transmissions count ($(length(sorted_txs))). " *
              "This is a simulator bug — encode_transcript must not skip transmissions.")
    end
    station_events = Dict(se.callsign => se.events for se in scene_events.station_events)
    total_dur = scene_events.total_duration

    # Build token list and times in same order as decoder (split label, expand)
    label = transcript.label
    parts = split(label)
    start_times = Float64[]
    end_times = Float64[]

    first_tx_start = isempty(sorted_txs) ? total_dur : sorted_txs[1].time_offset
    tx_idx = 0
    char_ranges_idx = 0
    char_ranges = Tuple{Float64, Float64}[]
    current_tx_start = 0.0
    current_tx_end = total_dur

    for (i, part) in enumerate(parts)
        if part == LABEL_SPECIAL_START
            push!(start_times, 0.0)
            push!(end_times, first_tx_start)
            continue
        end
        if part == LABEL_SPECIAL_END
            push!(start_times, current_tx_end)
            push!(end_times, total_dur)
            continue
        end
        if part == LABEL_SPECIAL_TS
            tx_idx += 1
            tx = sorted_txs[tx_idx]
            (call, s, e) = scene_events.transmission_ranges[tx_idx]
            evs = get(station_events, call, nothing)
            if evs === nothing
                error("compute_token_timings: no events for station \"$call\" " *
                      "(transmission $tx_idx). This is a simulator bug.")
            end
            if (s < 1 || e > length(evs))
                error("compute_token_timings: event range ($s:$e) out of bounds " *
                      "for station \"$call\" with $(length(evs)) events. This is a simulator bug.")
            end
            current_tx_start = evs[s].start_time
            ev = evs[e]
            current_tx_end = ev.start_time + ev.duration
            seg_evs = evs[s:e]
            char_ranges = character_time_ranges(tx.text, seg_evs)
            char_ranges_idx = 0
            push!(start_times, current_tx_start)
            push!(end_times, current_tx_start)
            continue
        end
        if part in LABEL_SPEAKER_TAGS
            push!(start_times, current_tx_start)
            push!(end_times, current_tx_start)
            continue
        end
        if part == LABEL_SPECIAL_TE
            push!(start_times, current_tx_end)
            push!(end_times, current_tx_end)
            continue
        end
        # Part is text (word or words): one token per character, same order as character_time_ranges
        for (ci, c) in enumerate(part)
            char_ranges_idx += 1
            if char_ranges_idx <= length(char_ranges)
                t_start, t_end = char_ranges[char_ranges_idx]
                push!(start_times, t_start)
                push!(end_times, t_end)
            else
                error("compute_token_timings: char_ranges exhausted at char '$c' " *
                      "(index $char_ranges_idx, have $(length(char_ranges)) ranges). " *
                      "character_time_ranges is out of sync with the label. " *
                      "Label part: \"$part\", tx_idx=$tx_idx.")
            end
        end
        # Space between parts (decoder adds space if next part is not special)
        if i < length(parts) && !(parts[i + 1] in LABEL_SPECIALS)
            char_ranges_idx += 1
            if char_ranges_idx <= length(char_ranges)
                t_start, t_end = char_ranges[char_ranges_idx]
                push!(start_times, t_start)
                push!(end_times, t_end)
            else
                error("compute_token_timings: char_ranges exhausted at inter-word space " *
                      "(index $char_ranges_idx, have $(length(char_ranges)) ranges). " *
                      "character_time_ranges is out of sync with the label. tx_idx=$tx_idx.")
            end
        end
    end

    (start_times, end_times)
end

"""
    time_to_frame(t_sec, n_frames, total_duration_sec, sample_rate, hop_size) -> Int

Map time in seconds to 1-based frame index. Frame j covers time
(j-1)*hop_size/sample_rate. Clamped to 1:n_frames.
"""
function time_to_frame(
    t_sec::Float64,
    n_frames::Int,
    total_duration_sec::Float64,
    sample_rate::Int,
    hop_size::Int,
)::Int
    # Frame center times: (j-1) * hop_size / sample_rate for j in 1:n_frames
    frame_idx = round(Int, t_sec * sample_rate / hop_size) + 1
    clamp(frame_idx, 1, n_frames)
end

"""
    token_timings_to_frames(start_times, end_times, n_frames, total_duration_sec, sample_rate, hop_size)
        -> (start_frames::Vector{Int}, end_frames::Vector{Int})

Convert token time ranges to 1-based frame indices.
"""
function token_timings_to_frames(
    start_times::Vector{Float64},
    end_times::Vector{Float64},
    n_frames::Int,
    total_duration_sec::Float64,
    sample_rate::Int,
    hop_size::Int,
)
    start_frames = Int[]
    end_frames = Int[]
    for i in 1:length(start_times)
        push!(start_frames, time_to_frame(start_times[i], n_frames, total_duration_sec, sample_rate, hop_size))
        push!(end_frames, time_to_frame(end_times[i], n_frames, total_duration_sec, sample_rate, hop_size))
    end
    (start_frames, end_frames)
end

"""
    compute_token_timing(transcript, scene_events, n_frames, total_duration_sec, sample_rate, hop_size)
        -> TokenTiming

Compute per-token frame alignment from simulator timing data. Always returns
TokenTiming; errors on inconsistency (which indicates a simulator bug).
"""
function compute_token_timing(
    transcript::Transcript,
    scene_events::SceneMorseEvents{Float64},
    n_frames::Int,
    total_duration_sec::Float64,
    sample_rate::Int,
    hop_size::Int,
)::TokenTiming
    start_times, end_times = compute_token_timings(transcript, scene_events)
    L = length(start_times)
    if length(end_times) != L
        error("compute_token_timing: start_times length ($L) != end_times length ($(length(end_times)))")
    end
    if L == 0
        error("compute_token_timing: empty timing vectors for label \"$(transcript.label)\"")
    end
    start_f, end_f = token_timings_to_frames(
        start_times, end_times, n_frames, total_duration_sec, sample_rate, hop_size,
    )
    TokenTiming(start_f, end_f)
end
